name: Test

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Tests
    uses: ./.github/workflows/test.yml
