name: Tests

on:
  workflow_call:

jobs:
  test:
    name: Maven-Java
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: aboutbits/github-actions-java/setup@v3
        with:
          java-version: 21
      - run: >-
          ./mvnw
          -s $GITHUB_WORKSPACE/.github/workflows/maven-settings.xml
          --batch-mode
          --fail-fast
          -Dsurefire.failIfNoSpecifiedTests=false
          test
        env:
          GITHUB_USER_NAME: ${{ github.actor }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
